"""
Service to run Pinnacle Export.
"""
import os
import tarfile
import tempfile
import shutil
import pydicom

from loguru import logger

from pymedphys.labs.pinnacle import PinnacleExport

from impit.framework import app, DataObject, celery

PINNACLE_EXPORT_SETTINGS_DEFAULTS = {
    "exportModalities": ["CT", "RTSTRUCT", "RTPLAN", "RTDOSE"],
}


@app.register("Pinnacle Export", default_settings=PINNACLE_EXPORT_SETTINGS_DEFAULTS)
def pinnacle_export_service(data_objects, working_dir, settings):
    """
    Implements the impit framework to provide a pinnacle tar export service
    """

    logger.info("Running Pinnacle Export")
    logger.info("Using settings: " + str(settings))

    return_objects = []
    for data_object in data_objects:
        logger.info("Running on data object: " + data_object.path)

        if not data_object.type == "FILE" or not tarfile.is_tarfile(data_object.path):
            logger.error(f"Can only process TAR file. Skipping file: {data_object.path}")
            continue

        archive_path = tempfile.mkdtemp()

        # Extract the tar archive
        tar = tarfile.open(data_object.path)
        for member in tar.getmembers():
            if not ":" in member.name:
                tar.extract(member, path=archive_path)

        # Read the path to the patient directory from the data object meta data
        pat_path = data_object.meta_data["patient_path"]
        pinn_extracted = os.path.join(archive_path, pat_path)

        pinn = PinnacleExport(pinn_extracted, None)

        # Find the plan we want to export in the list of plans
        if len(pinn.plans) == 0:
            logger.error("No Plans found for patient")
            continue

        export_plan = None
        for plan in pinn.plans:
            if (
                "plan_name" in data_object.meta_data.keys()
                and plan.plan_info["PlanName"] == data_object.meta_data["plan_name"]
            ):
                export_plan = plan
                break

            if export_plan is None:
                export_plan = plan

        # If a trial was given, try to find it and set it
        for trial in export_plan.trials:
            trial_name = trial["Name"]
            if (
                "trial" in data_object.meta_data.keys()
                and trial_name == data_object.meta_data["trial"]
            ):
                export_plan.active_trial = trial_name

        output_dir = os.path.join(working_dir, str(data_object.id))
        if os.path.exists(output_dir):
            # Just in case it was already run for this data object, lets remove all old output
            shutil.rmtree(output_dir)
        os.makedirs(output_dir)

        if "CT" in settings["exportModalities"]:
            logger.info("Exporting Primary CT")
            pinn.export_image(export_plan.primary_image, export_path=output_dir)

        if "RTSTRUCT" in settings["exportModalities"]:
            logger.info("Exporting RTSTRUCT")
            pinn.export_struct(export_plan, output_dir)

        if "RTPLAN" in settings["exportModalities"]:
            logger.info("Exporting RTPLAN")
            pinn.export_plan(export_plan, output_dir)

        if "RTDOSE" in settings["exportModalities"]:
            logger.info("Exporting RTDOSE")
            pinn.export_dose(export_plan, output_dir)

        # Find the output files
        output_objects = [os.path.join(output_dir, f) for f in os.listdir(output_dir)]

        # Create the output data objects
        for obj in output_objects:

            # Add some private headers to the data objects
            file_name = os.path.basename(obj)
            if file_name.startswith("R"):  # Don't add to the image series

                dicom_dataset = pydicom.read_file(obj)

                # Add some predefined tags
                block = dicom_dataset.private_block(0x000B, "Pinnacle Export Tool", create=True)
                block.add_new(0x01, "LO", "Generated by Pinnacle Export Service")
                block.add_new(0x02, "LO", export_plan.active_trial["Name"])
                block.add_new(
                    0x03, "DA", export_plan.active_trial["ObjectVersion"]["WriteTimeStamp"]
                )

                if export_plan.plan_info["PlanIsLocked"]:
                    block.add_new(0x04, "LO", "Pinnacle Plan: LOCKED")
                else:
                    block.add_new(0x04, "LO", "Pinnacle Plan: UNLOCKED")

                if dicom_dataset.Modality == "RTPLAN":
                    block.add_new(
                        0x05,
                        "LO",
                        "WARNING: OUTPUT GENERATED FOR RTPLAN FILE IS "
                        "UNVERIFIED AND MOST LIKELY INCORRECT!",
                    )

                # Also add all meta data sent with this object as a tag
                block = dicom_dataset.private_block(
                    0x000D, "Pinnacle Export Meta Data", create=True
                )
                dicom_meta = pydicom.Sequence()
                for meta_data_key in data_object.meta_data.keys():
                    dicom_meta_ds = pydicom.Dataset()
                    meta_block = dicom_meta_ds.private_block(0x000B, meta_data_key, create=True)
                    meta_block.add_new(0x01, "LO", data_object.meta_data[meta_data_key])
                    dicom_meta.append(dicom_meta_ds)
                block.add_new(0x01, "SQ", dicom_meta)

                # Use explicit VR to write private blocks cleanly
                dicom_dataset.file_meta.TransferSyntaxUID = "1.2.840.10008.1.2.1"
                dicom_dataset.is_implicit_VR = False

                dicom_dataset.save_as(obj)

            output_data_object = DataObject(type="DICOM", path=obj, parent=data_object)
            return_objects.append(output_data_object)

    logger.info("Finished Pinnacle Export")

    return return_objects


if __name__ == "__main__":

    # Run app by calling "python service.py" from the command line

    DICOM_LISTENER_PORT = 7777
    DICOM_LISTENER_AETITLE = "PINNACLE_EXPORT_SERVICE"

    app.run(
        debug=True,
        host="0.0.0.0",
        port=8001,
        dicom_listener_port=DICOM_LISTENER_PORT,
        dicom_listener_aetitle=DICOM_LISTENER_AETITLE,
    )
